name: Build the documentation and the UI

on: [pull_request, push]

jobs:
  docs_and_ui:
    name: Build the Documantation and UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean docs
        run: |
          if [ -d docs/build/ui ]; then rm -R docs/build/ui; fi
        shell: bash
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Generate templates
        run: |
          npm install nunjucks
          node_modules/nunjucks/bin/precompile ebu_tt_live/ui/user_input_producer/template/user_input_producer_template.xml > ebu_tt_live/ui/user_input_producer/template/user_input_producer_template.js
          node_modules/nunjucks/bin/precompile ebu_tt_live/ui/user_input_producer/template/live_message_template.xml > ebu_tt_live/ui/user_input_producer/template/live_message_template.js
      - name: Copy UI files into place
        run: |
          mkdir -p docs/build/ui
          cp -R ebu_tt_live/ui/user_input_producer docs/build/ui/
          cp -R ebu_tt_live/ui/test docs/build/ui/
          cp -R ebu_tt_live/ui/assets docs/build/ui/user_input_producer/
          cp -R ebu_tt_live/ui/assets docs/build/ui/test/
        shell: bash
      - name: Setup graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Build the documentation
        run: |
          python setup.py build_sphinx
      - name: Publish to GitHub Pages
        env:
          REF_NAME: ${{ github.ref }}
        if: ${{ 'refs/head/master' == env.REF_NAME }}
        run: |
          echo "This is a push to master branch, pushing build output to github-pages"
      - name: Skip publishing to GitHub Pages
        env:
          REF_NAME: ${{ github.ref }}
        if: ${{ 'refs/head/master' != env.REF_NAME }}
        run: |
          echo "This is NOT a push to master branch, not pushing to github-pages"
