name: Check the tests pass

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Install and build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
          cache: 'pip'
      - name: Install older pip
        run: |
          python -m pip install pip==20.3.4
        shell: bash
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        shell: bash
      - name: Generate bindings
        run: |
          pyxbgen --binding-root=./ebu_tt_live/bindings -m __init__ --schema-root=./ebu_tt_live/xsd/ -r -u ebutt_all.xsd
        shell: bash
      - name: Test
        run: |
          python setup.py test
        shell: bash
      - name: Install coveralls
        run: |
          pip install "coveralls<2"
        shell: bash
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
      - name: Build notification
        if: always()
        uses: edge/simple-slack-notify@v1.1.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#ci'
          status: ${{ job.status }}
          success_text: 'Build (#${env.GITHUB_RUN_NUMBER}) completed successfully'
          failure_text: 'Build (#${env.GITHUB_RUN_NUMBER}) failed'
          cancelled_text: 'Build (#${env.GITHUB_RUN_NUMBER}) was cancelled'
          fields: |
            [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
