name: Check the tests pass

on: pull_request

jobs:
  build:
    name: Install and build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
          cache: 'pip'
      - name: Install older pip
        run: |
          python -m pip install pip==20.3.4
        shell: bash
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        shell: bash
      - name: Generate bindings
        run: |
          pyxbgen --binding-root=./ebu_tt_live/bindings -m __init__ --schema-root=./ebu_tt_live/xsd/ -r -u ebutt_all.xsd
        shell: bash
      - name: Test
        run: |
          python setup.py test
        shell: bash
      - name: Install coveralls
        run: |
          pip install "coveralls<2"
        shell: bash
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
      # At this point we would like to report coverage, but this doesn't work with Python 2.7
      # - name: Install coveragepy-lcov
      #   run: |
      #     pip install coveragepy-lcov
      # - name: Convert .coverage to lcov.info
      #   run: |
      #     coveragepy-lcov
      # - name: Coveralls GitHub Action
      #   uses: coverallsapp/github-action@1.1.3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: lcov.info
