name: Check the tests pass

on: pull_request

jobs:
  build:
    name: Install and build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
          cache: 'pip'
      - name: Install older pip
        run: |
          python -m pip install pip==20.3.4
        shell: bash
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        shell: bash
      - name: Generate bindings
        run: |
          pyxbgen --binding-root=./ebu_tt_live/bindings -m __init__ --schema-root=./ebu_tt_live/xsd/ -r -u ebutt_all.xsd
        shell: bash
      - name: Test
        run: |
          python setup.py test
        shell: bash
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install coveragepy-lcov
      - name: Convert to lcov
        run: |
          coveragepy-lcov
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
