name: Check the tests pass

on: pull_request

jobs:
  build:
    name: Install and build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Python 3.7
        uses: actions/setup-python@main
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      - name: Generate bindings
      run: |
        pyxbgen --binding-root=./ebu_tt_live/bindings -m __init__ --schema-root=./ebu_tt_live/xsd/ -r -u ebutt_all.xsd

  test:
    name: Run tests with pytest
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Run tests with pytest
      run: |
        python setup.py test
